# https://circleci.com/docs/2.0/language-java/

version: 2.1
jobs:
  build:
    docker:
      # check for new versions: https://circleci.com/docs/2.0/circleci-images/#openjdk
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout

      - restore_cache:
          key: circleci-jOrchestra-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-jOrchestra-{{ checksum "pom.xml" }}

      - run: mvn clean package # run the actual tests
